services:
  client:
    volumes:
      - /app/node_modules
      - ./client/:/app/
    build: 
      context: ./client
    ports:
      - "3000:3000"

  server:
    volumes:
      - /app/node_modules
      - ./server/:/app
    build: 
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db

  mysql_db:
    container_name: pirosquare_mysql_db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./server/db/mysql:/var/lib/mysql
      - ./db/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      # init.sql 경로 : 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"